# -*- coding: utf-8 -*-
"""TI03_Indri Rachma_0110223101

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p9F3TV9J8GNqNHcrNMBBt29jdJal3_Oj
"""

import pandas as pd

# Baca file dan tampilkan seluruh data
data_file = ('/content/500_Person_Gender_Height_Weight_Index.csv')
data = pd.read_csv(data_file)

# Tampilkan seluruh data
print(data)

# Hitung jumlah data berdasarkan Gender
jumlah_data = data.groupby('Gender').agg(
    Jumlah_Data=('Height', 'count')
).reset_index()

# Tampilkan hasil
print(jumlah_data)

# Hitung rata-rata tinggi dan berat badan berdasarkan Gender
rata_rata = data.groupby('Gender').agg(
    Rata_Rata_Height=('Height', 'mean'),
    Rata_Rata_Weight=('Weight', 'mean')
).reset_index()

# Tampilkan hasil
print(rata_rata)

# Hitung nilai maksimum tinggi dan berat badan berdasarkan Gender
nilai_max = data.groupby('Gender').agg(
    Nilai_Max_Height=('Height', 'max'),
    Nilai_Max_Weight=('Weight', 'max')
).reset_index()

# Tampilkan hasil
print(nilai_max)

# Hitung nilai minimum tinggi dan berat badan berdasarkan Gender
nilai_min = data.groupby('Gender').agg(
    Nilai_Min_Height=('Height', 'min'),
    Nilai_Min_Weight=('Weight', 'min')
).reset_index()

# Tampilkan hasil
print(nilai_min)

# Ubah kolom Gender menjadi data binary
data['Gender'] = data['Gender'].replace({'Female': 0, 'Male': 1})

# Tampilkan data yang telah diperbarui
print(data.head())

import seaborn as sns
import matplotlib.pyplot as plt

# Membuat grafik indeks BMI berdasarkan Gender
plt.figure(figsize=(10, 6))
sns.countplot(data=data, x='Index', hue='Gender', palette='pastel')

# Menambahkan label dan judul
plt.title('Distribusi Indeks BMI Berdasarkan Gender')
plt.xlabel('Indeks BMI')
plt.ylabel('Jumlah')
plt.xticks(ticks=range(6), labels=[
    'Extremely Weak',
    'Weak',
    'Normal',
    'Overweight',
    'Obesity',
    'Extreme Obesity'
])
plt.legend(title='Gender', labels=['Female (0)', 'Male (1)'])
plt.show()